### ISSUE TITLE
Separate DTO and Entity

### ISSUE THREAD

**Issue by truchjan** [truchjan/LundegaardContactForm#4]
- Typicky je vhodné oddělit objekty, se kterými pracují controllery (DTO) a servisní a repository vrstva (Entity)

**Comment by truchjan** [comment]
S flyway jsem nikdy nepracoval, takže jsem zatím hledal na internetu různé příklady a většina jich používá spring.jpa.hibernate.ddl-auto=validate, to už je do produkce v pořádku?

- validate je do produkce v poradku, overi, jestli to co nasadil flyway neni v rozporu s modelem v hibernate, ale nezasahne nekontrolovane do DB

**Comment by truchjan** [comment]
Není mi moc jasné: "Typicky je vhodné oddělit objekty, se kterými pracují controllery (DTO) a servisní a repository vrstva (Entity)". Chápu to tak, že budu mít například PersonDTO(stejné hodnoty jako Person), se kterým bude pracovat PersonController, ale service a repository bude stále pracovat s Entity?

- chapete to spravne. S lombok a pripadne mapstruct (take doporucuji kouknout) jsou dto jednoduche a mapovani bez prace. Typicky servisni vrstva v API vystavuje DTO, ktere pro potreby repositories meni na entity.
narazite i na clanky, kde se doporucuje vystavit na servisni vrstve jiz entity, oboje je v poradku a zalezi na konkretni situaci

**Comment by truchjan** [comment]
Bohužel se mi nepodařilo použít mapstruct, nešlo mi využít anotaci @Mapper, která podle popisu pluginu do intellij idea momentálně nefunguje. Našel jsem spoustu dalších metod jak na sebe entity/dto namapovat a jednu z nich využil. Přijde mi trochu nepřehledná, ale funguje. Doufám, že jsem zadání správně pochopil a splnil dle vašich představ.

**Comment by LZaruba** [comment]
Muze byt problem s kombinaci lombok a mapstruct (oboje pouziva annotation processing). Osetrujeme to nasledujicim konstruktem v pom.xml -> build -> plugins:

`<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>11</source>
                    <release>11</release>
                    <compilerArgument>-parameters</compilerArgument>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>
                            -Amapstruct.defaultComponentModel=spring
                        </compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>`
